version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: matsumoto
      POSTGRES_PASSWORD: assassin
      PASSWORD: assassin119282
      POSTGRES_DB: Omailey
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    user: root
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d